# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths:
      -'**.html'

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deploy to Kars
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf song-browser
          cd /var/www/html/songs 
          git clone https://github.com/gooish/song-browser.git
          mv song-browser/index.html .
          rm -rf song-browser
          
